### ISSUE TITLE
[BUG] Upgrading to version 17.3.0 breaks navigation on gatsby 4

### ISSUE THREAD

**Issue by KuSh** [microsoft/applicationinsights-react-js#105]
**Description/Screenshot**

After upgrading applicationinsights-react-js from version 3.4.3 to version 17.3.0 and applicationinsights-web from version 2.8.18 to version 3.3.0 on our gatsby app, client side routing broke. Reverting to previous versions restore expected behavior

**Steps to Reproduce**

 - OS/Browser: I use MacOS 14.5 / Firefox 129.0 but the problem has also been observed on Windows and Linux with Chrome or Edge  
 - React Version: 18.3.1
 - SDK Version [e.g. 22]: 3.3.0
 - How you initialized the SDK: yes

**Expected behavior**
Navigation works

**Additional context**
Upgrading working app based on :
- gatsby 4.25.9
- @gatsbyjs/reach-router@1.3.9

SDK initialized with :
```tsx
import { globalHistory } from '@gatsbyjs/reach-router';
import { ReactPlugin } from '@microsoft/applicationinsights-react-js';
import { ApplicationInsights } from '@microsoft/applicationinsights-web';

const reactPlugin = new ReactPlugin();
const appInsights = new ApplicationInsights({
  config: {
    connectionString: process.env.GATSBY_APPLICATION_INSIGHTS_KEY,
    extensions: [reactPlugin],
    extensionConfig: {
      [reactPlugin.identifier]: { history: globalHistory },
    },
    enableAjaxErrorStatusText: true,
    enableAjaxPerfTracking: true,
    enableRequestHeaderTracking: true,
    enableResponseHeaderTracking: true,
    enableUnhandledPromiseRejectionTracking: true,
  },
});
appInsights.loadAppInsights();
```

**Comment by MSNev** [comment]
Can you please provide details on what you mean by "broke" and maybe a simple example, as we don't have experience with the Gatsby environment. 

Is it potentially a different in the way react is handling the history object / implementation?

**Comment by MSNev** [comment]
Can you also review https://microsoft.github.io/ApplicationInsights-JS/upgrade/v3_BreakingChanges.html to ensure that your issue is not caused by some known breaking change?

As the upgrade made some (internally) significant changes and the passed in configuration is now used as a template and not directly. If you are getting an error on initialization due to the history object having (internal) recursive references then we may need to provide some work arounds (although in the latest version we believe we have addressed all of the known issues)

**Comment by KuSh** [comment]
Hi @MSNev,

By broke I mean that after upgrade when clicking on a link in our app, the URL on the browser navbar changes but not the page content. Reverting to previous version fixes it.

I have reviewed the breaking changes page and didn't see anything that seems wrong. I'm using the react plugin as documented on your doc and the history provided by reach router globalHistory is based on window.location, see https://github.com/gatsbyjs/reach-router/blob/20fcc5e6035b90830f8bafdbad5ff03fbe479f2e/src/lib/history.js#L153

If you need more info just ask

Regards, KuSh

**Comment by MSNev** [comment]
That is a little weird, looking at your code and ours, we are both just listening to the location history events (like popstate), so we should both be getting called -- unlike some of our other hooks where we "replace" the entry point object with our own shimmed (wrapper) version to handle intercepting the call -- that is not the case for this one....

Are your handlers getting called?

To me this sounds like something is causing a JS error which is halting the "switching" (somehow), I'll let @siyuniu-ms try and dig in to review, but one of the first things I'd check would be to see if someone else in the gatsby, react (v17) etc and look for JS errors either on the console (or any global error catcher), there may or may not be an "Exception" event being sent by Application Insights as we are listening only to the global `window.onerror` and most frameworks (React) install their own global error handler so we actually end up never seeing it (it's one of the hooks that the React Extension adds, so we can see the error).

**Comment by siyuniu-ms** [comment]
@KuSh Hi, could you check https://github.com/siyuniu-ms/gatsby-starter-blog? I used your code and created this demo project. When I run it, the router works good.

**Comment by KuSh** [comment]
Hi @siyuniu-ms as stated in my bug report I'm currently using gatsby v4 and associated @gatsbyjs/reach-router v1, and I'm able to reproduce the problem in that case, see https://github.com/KuSh/my-gatsby-site when navigating on pages /1 to /5

Upgrading to gatsby 5 and @gatsbyjs/reach-router 2 seems to fix the problem but it's not possible at the moment

**Comment by siyuniu-ms** [comment]
Hi @KuSh,

Thank you for your patience, and sorry for the delayed response!

After investigating, it's a bit challenging to pinpoint the exact root cause. However, I took a closer look at the code in the @gatsbyjs/reach-router package and came across this PR: [gatsbyjs/reach-router#4](https://github.com/gatsbyjs/reach-router/pull/4). This PR introduces significant changes made to align with React 18, particularly around hooks and context usage.

Based on this, I suspect that your project is using React 18, which extensively utilizes hooks. Our React package is also hook-based, whereas reach/router v1 is not. This difference could explain why the router change detection doesn't work with reach/router v1 but functions correctly with v2, which has been updated for React 18 compatibility.

Let me know if this aligns with your observations or if you'd like further assistance troubleshooting!

Best regards,

**Comment by KuSh** [comment]
Hi @siyuniu-ms thanks for your response and your detailed explanation !

We are migrating away from gatsby and migrating away from reach-router is also on our technical roadmap so I'll mark it as a requirement to upgrade applicationinsights 👍

Thanks again,
regards,
