### ISSUE TITLE
AppInsightsErrorBoundary:  Add custom property

### ISSUE THREAD

**Issue by larlew** [microsoft/applicationinsights-react-js#21]
Maybe this is already possible?
I would like to add a custom property when the AppInsightsErrorBoundary logs an error to AppInsights.
For example, I would like to add the software version that the error occurred in.  

Is this possible by adding a new property to the AppInsightsErrorBoundary?  
or should I try to catch the exception, add my version number to it, rethrow, and let it bubble back up to the AppInsightsErrorBoundary?

Finally, is there just just add default properties to TrackException from the config or something?

**Comment by E-PressSend** [comment]
yeah that would be helpful.

I don't see any way of doing it at the moment

**Comment by MSNev** [comment]
You could do this by using a telemetry initializer, which is called for every event. So you could then either add this just for the exceptions or for every event -- not exactly what your asking for but is a way to achieve it.

We need to provide more complete documentation for this but here are a few links
https://github.com/Microsoft/ApplicationInsights-JS#telemetry-initializers
https://github.com/Microsoft/ApplicationInsights-JS#telemetry-initializers

Things to note, because this is called for every event you should check that the contents of the event are as expected and not assume that an embedded object always exists (because it may not) as this will cause a Javascript exception, the event(s) will still get sent but you may not always have the changes you want.

eg.
`envelope.tags["myTag"] = "fred";` Assumes that the `tags` object always exists. A safer option is something like `(envelope.tags = envelope.tags || {})["myTag"]` so it will assign an empty object to the tags if not already present.
